name: Monitor EC2


on: 
  push: 
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Clone
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Packages
        run: npm install

      - name: Run the Test
        run: npm run test

      - name: Print the Hello.txt file
        run: cat hello.txt
# another job
  Deploy:
    runs-on: self-hosted
    needs: Test

    steps:
      - name: Create a folder
        run: |
          cd ~
          pwd
          mkdir -p monitor
          cd monitor
          touch hello.txt
          echo "Hello World" > hello.txt
          cat hello.txt